name: Reusable run example
on: [ workflow_call ]
inputs:
  folder-path:
    description: 'folder path where we want to run the tests'
    required: 'false'
    default: '.'
runs:
  strategy:
    matrix:
      rule: ["all", "clean", "fclean", "re", "debug", "redebug"]
  using: "composite"
  steps:
    - run: make ${{ matrix.rule }}
      shell: bash
      working-directory: ${{ inputs.folder-path }}
