name: Reusable run example
on: [ workflow_call ]
inputs:
  folder-path:
    description: 'folder path where we want to run the tests'
    required: 'false'
    default: '.'
runs:
  using: "composite"
  steps:
    - run: ./tests/scripts/functional_tests.bash
      shell: bash
      working-directory: ${{ inputs.folder-path }}
