name: Reusable run example
on: [ workflow_call ]
inputs:
  folder-path:
    description: 'folder path where we want to run the tests'
    required: 'false'
    default: '.'
runs:
  using: "composite"
  steps:
    - run: make all
      shell: bash
      working-directory: ${{ inputs.folder-path }}
    - run: $(grep NAME < config.mk | cut -d'=' -f2)
      shell: bash
      working-directory: ${{ inputs.folder-path }}
    - run: make clean
      shell: bash
      working-directory: ${{ inputs.folder-path }}
    - run: make fclean
      shell: bash
      working-directory: ${{ inputs.folder-path }}
    - run: make re
      shell: bash
      working-directory: ${{ inputs.folder-path }}
    - run: make debug
      shell: bash
      working-directory: ${{ inputs.folder-path }}
    - run: make redebug
      shell: bash
      working-directory: ${{ inputs.folder-path }}
