name: Main
on: [ push, pull_request ]
jobs:
  Check_scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: shellcheck $(find . -name "*.bash" -o -name "*.sh")

  Units:
    runs-on: ubuntu-latest
    needs: [ Check_scripts ]
    strategy:
      fail-fast: false
      matrix:
        folder: [
          "1-minimal"
        ]
    name: "Unit: On ${{ matrix.folder }}"
    steps:
      - uses: actions/checkout@v2
      - run: ./test.bash
        shell: bash
        working-directory: tests/units/${{ matrix.folder }}

  # If the following test fails, it means the number of examples have changed
  # Modify this test, and the list of examples in test 'Functional_Tests'
  Functional_Tests_Regression:
    runs-on: ubuntu-latest
    needs: [ Check_scripts ]
    steps:
      - uses: actions/checkout@v2
      - run: test "$(ls -1 examples | wc -l)" -eq 6

  Functional_Tests:
    runs-on: ubuntu-latest
    needs: [ Check_scripts ]
    strategy:
      fail-fast: false
      matrix:
        folder: [
          "1-hello-world",
          "2-sum100",
          "3-fibonacci",
          "4-fib-gcc",
          "5-subdirs",
          "6-debug"
        ]
    name: "FT: On ${{ matrix.folder }}"
    steps:
      - uses: actions/checkout@v2
      - run: ../../tests/scripts/functional_tests.bash
        shell: bash
        working-directory: examples/${{ matrix.folder }}
