name: Main
on: [ push, pull_request ]
jobs:

  functional_tests:
    strategy:
      matrix:
        folder: [
          "examples/1-hello-world",
          "examples/2-sum100",
          "examples/3-fibonacci",
          "examples/4-fib-gcc",
          "examples/5-subdirs",
          "examples/6-debug"
        ]
    runs-on: ubuntu-latest
    name: On ${{ matrix.folder }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/run_example
        with:
          folder-path: ${{ matrix.folder }}

  regressiontest-equals6:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: test "$(ls -1 examples | wc -l)" -eq 6
