name: Main
on: [ push, pull_request ]
jobs:

  functional_tests_regression:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: test "$(ls -1 examples | wc -l)" -eq 6

  functional_tests:
    runs-on: ubuntu-latest
    needs: [ functional_tests_regression ]
    strategy:
      fail-fast: false
      matrix:
        folder: [
          "examples/1-hello-world",
          "examples/2-sum100",
          "examples/3-fibonacci",
          "examples/4-fib-gcc",
          "examples/5-subdirs",
          "examples/6-debug"
        ]
    name: On ${{ matrix.folder }}
    steps:
      - uses: actions/checkout@v2
      - run: ../../tests/scripts/functional_tests.bash
        shell: bash
        working-directory: ${{ matrix.folder }}
