name: Main
on: [ push, pull_request ]
jobs:
  Check_scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: shellcheck -x $(find . -name "*.bash" -o -name "*.sh")

  # If the following test fails, it means the number of examples have changed
  # Modify this test, and the list of examples in job 'Compilation'
  Compilation_Prevent:
    runs-on: ubuntu-latest
    needs: [ Check_scripts ]
    steps:
      - uses: actions/checkout@v2
      - run: test "$(find examples -mindepth 1 -maxdepth 1 | wc -l)" -eq 6

  Compilation:
    runs-on: ubuntu-latest
    needs: [ Check_scripts ]
    strategy:
      fail-fast: false
      matrix:
        folder: [
          "1-hello-world",
          "2-sum100",
          "3-fibonacci",
          "4-fib-gcc",
          "5-subdirs",
          "6-debug"
        ]
    name: "Comp: On examples/${{ matrix.folder }}"
    steps:
      - uses: actions/checkout@v2
      - run: ../../tests/compilation/all.bash
        shell: bash
        working-directory: examples/${{ matrix.folder }}

  Configuration:
    runs-on: ubuntu-latest
    needs: [ Check_scripts ]
    name: Configuration on mini-project
    steps:
      - uses: actions/checkout@v2
      - run: ../all.bash
        shell: bash
        working-directory: tests/configuration/mini-project

  Error-Handling:
    runs-on: ubuntu-latest
    needs: [ Check_scripts ]
    name: Error-handling on mini-project2
    steps:
      - uses: actions/checkout@v2
      - run: ../all.bash
        shell: bash
        working-directory: tests/error-handling/mini-project2
