name: Main
on: [ push, pull_request ]
jobs:

  example:
    strategy:
      matrix:
        folder: ["examples/1-hello-world", "examples/2-sum100"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/run_example
        with:
          folder-path: ${{ matrix.folder }}

  regressiontest-equals6:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: test "$(ls -1 examples | wc -l)" -eq 6
